channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.7.5
  - pip
  # Above, list any packages that MUST be installed via conda
  - pip:
    # Install all pip-installable packages
    - -r file:requirements.txt
