# This is a basic workflow to test the package build under various python versions
name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the stable branch
on:
  push:
    branches:
      - stable
      - develop
  pull_request:
    branches:
      - stable
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Step 1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Step 2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      # Step 3
      - name: Run tests
        # Run tox using the version of Python in `PATH`
        # See https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#running-tests-with-tox
        run: tox -e py
